### ISSUE TITLE
Installing twice

### ISSUE THREAD

**Issue by tmcclintock** [beckermr/cosmocalc#1]
I ran into a really strange issue that you might not want to bother looking into. Basically, I attempted to install on a new machine, and it compiled fine but failed at the point where it adds files to the site-packages directory. This was because I was using a version of python in another user's directory that I didn't have write access to.

So then I installed a local version of python and attempted to reinstall. This failed again however, because cosmocalc.py and cosmocalc.pyc were still trying to be written to the old site-packages directory (as opposed to the local one).

I solved the problem by just re-cloning the repo and doing a fresh install into the local python directory structure.

Like I said, this case is so obscure you might not care to fix it.

**Comment by beckermr** [comment]
I don't know what happened here, but usually if you remove the `build` dir before redoing the setup, things should work. I am going to close this issue for now, since I am guessing this is something having to do with distutils.
